[2021-02-16 12:11:04,807] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-02-14T00:00:00+00:00 [queued]>
[2021-02-16 12:11:05,324] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-02-14T00:00:00+00:00 [queued]>
[2021-02-16 12:11:05,355] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-16 12:11:05,362] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-16 12:11:05,363] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-16 12:11:05,689] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_0> on 2021-02-14T00:00:00+00:00
[2021-02-16 12:11:05,803] {standard_task_runner.py:52} INFO - Started process 49 to run task
[2021-02-16 12:11:05,847] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2021-02-14T00:00:00+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpgnvio0mo', '--error-file', '/tmp/tmp6kprhj6v']
[2021-02-16 12:11:05,863] {standard_task_runner.py:77} INFO - Job 3: Subtask runme_0
[2021-02-16 12:11:17,321] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_0 2021-02-14T00:00:00+00:00 [running]> on host 071a2d8d0e8e
[2021-02-16 12:11:19,454] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_0
AIRFLOW_CTX_EXECUTION_DATE=2021-02-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-14T00:00:00+00:00
[2021-02-16 12:11:19,497] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-16 12:11:19,516] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_0__20210214" && sleep 1
[2021-02-16 12:11:19,958] {bash.py:169} INFO - Output:
[2021-02-16 12:11:20,019] {bash.py:173} INFO - example_bash_operator__runme_0__20210214
[2021-02-16 12:11:21,127] {bash.py:177} INFO - Command exited with return code 0
[2021-02-16 12:11:22,267] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20210214T000000, start_date=20210216T121104, end_date=20210216T121122
[2021-02-16 12:11:23,163] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-02-16 12:11:23,270] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 49
[2021-02-16 12:11:23,280] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-16 12:11:23,297] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-02-16 12:11:24,237] {process_utils.py:66} INFO - Process psutil.Process(pid=49, status='terminated', exitcode=1, started='12:11:05') (49) terminated with exit code 1
