[2021-02-18 10:50:32,962] {scheduler_job.py:182} INFO - Started process (PID=291) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:50:32,965] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:50:32,967] {logging_mixin.py:104} INFO - [2021-02-18 10:50:32,967] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:50:32,983] {logging_mixin.py:104} INFO - [2021-02-18 10:50:32,981] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:50:32,986] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:50:33,011] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.056 seconds
[2021-02-18 10:51:03,115] {scheduler_job.py:182} INFO - Started process (PID=318) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:51:03,117] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:51:03,119] {logging_mixin.py:104} INFO - [2021-02-18 10:51:03,119] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:51:03,129] {logging_mixin.py:104} INFO - [2021-02-18 10:51:03,128] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:51:03,131] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:51:03,173] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.063 seconds
[2021-02-18 10:51:33,775] {scheduler_job.py:182} INFO - Started process (PID=345) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:51:33,780] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:51:33,786] {logging_mixin.py:104} INFO - [2021-02-18 10:51:33,786] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:51:33,796] {logging_mixin.py:104} INFO - [2021-02-18 10:51:33,795] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:51:33,800] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:51:33,828] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.059 seconds
[2021-02-18 10:52:04,498] {scheduler_job.py:182} INFO - Started process (PID=372) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:52:04,505] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:52:04,507] {logging_mixin.py:104} INFO - [2021-02-18 10:52:04,506] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:52:04,515] {logging_mixin.py:104} INFO - [2021-02-18 10:52:04,514] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:52:04,517] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:52:04,537] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.044 seconds
[2021-02-18 10:52:34,690] {scheduler_job.py:182} INFO - Started process (PID=399) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:52:34,694] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:52:34,696] {logging_mixin.py:104} INFO - [2021-02-18 10:52:34,696] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:52:34,708] {logging_mixin.py:104} INFO - [2021-02-18 10:52:34,707] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:52:34,710] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:52:34,747] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.061 seconds
[2021-02-18 10:53:04,996] {scheduler_job.py:182} INFO - Started process (PID=426) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:53:05,003] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:53:05,005] {logging_mixin.py:104} INFO - [2021-02-18 10:53:05,004] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:53:05,012] {logging_mixin.py:104} INFO - [2021-02-18 10:53:05,011] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:53:05,015] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:53:05,040] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.048 seconds
[2021-02-18 10:53:35,639] {scheduler_job.py:182} INFO - Started process (PID=453) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:53:35,651] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:53:35,653] {logging_mixin.py:104} INFO - [2021-02-18 10:53:35,653] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:53:35,664] {logging_mixin.py:104} INFO - [2021-02-18 10:53:35,663] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:53:35,668] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:53:35,704] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.071 seconds
[2021-02-18 10:54:05,796] {scheduler_job.py:182} INFO - Started process (PID=480) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:54:05,799] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:54:05,800] {logging_mixin.py:104} INFO - [2021-02-18 10:54:05,800] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:54:05,811] {logging_mixin.py:104} INFO - [2021-02-18 10:54:05,810] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:54:05,813] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:54:05,845] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.053 seconds
[2021-02-18 10:54:36,603] {scheduler_job.py:182} INFO - Started process (PID=507) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:54:36,607] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:54:36,609] {logging_mixin.py:104} INFO - [2021-02-18 10:54:36,609] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:54:36,618] {logging_mixin.py:104} INFO - [2021-02-18 10:54:36,617] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:54:36,621] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:54:36,653] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.086 seconds
[2021-02-18 10:55:07,339] {scheduler_job.py:182} INFO - Started process (PID=534) to work on /opt/airflow/dags/koko.py
[2021-02-18 10:55:07,349] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/koko.py for tasks to queue
[2021-02-18 10:55:07,351] {logging_mixin.py:104} INFO - [2021-02-18 10:55:07,351] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/koko.py
[2021-02-18 10:55:07,360] {logging_mixin.py:104} INFO - [2021-02-18 10:55:07,359] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/koko.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/koko.py", line 65
    dag=dag
      ^
SyntaxError: invalid syntax
[2021-02-18 10:55:07,362] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/koko.py
[2021-02-18 10:55:07,389] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/koko.py took 0.077 seconds
