[2021-02-16 12:11:27,408] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_1 2021-02-16T12:09:42.897859+00:00 [queued]>
[2021-02-16 12:11:27,835] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_1 2021-02-16T12:09:42.897859+00:00 [queued]>
[2021-02-16 12:11:27,850] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-16 12:11:27,851] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-16 12:11:27,853] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-16 12:11:28,462] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_1> on 2021-02-16T12:09:42.897859+00:00
[2021-02-16 12:11:28,798] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_1', '2021-02-16T12:09:42.897859+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp68iburkn', '--error-file', '/tmp/tmpwrg1yl6_']
[2021-02-16 12:11:28,802] {standard_task_runner.py:77} INFO - Job 8: Subtask runme_1
[2021-02-16 12:11:28,581] {standard_task_runner.py:52} INFO - Started process 53 to run task
[2021-02-16 12:11:29,712] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_1 2021-02-16T12:09:42.897859+00:00 [running]> on host 071a2d8d0e8e
[2021-02-16 12:11:32,009] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_1
AIRFLOW_CTX_EXECUTION_DATE=2021-02-16T12:09:42.897859+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-16T12:09:42.897859+00:00
[2021-02-16 12:11:32,049] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-16 12:11:32,097] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_1__20210216" && sleep 1
[2021-02-16 12:11:32,304] {bash.py:169} INFO - Output:
[2021-02-16 12:11:32,508] {bash.py:173} INFO - example_bash_operator__runme_1__20210216
[2021-02-16 12:11:33,649] {bash.py:177} INFO - Command exited with return code 0
[2021-02-16 12:11:34,549] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_1, execution_date=20210216T120942, start_date=20210216T121127, end_date=20210216T121134
[2021-02-16 12:11:35,497] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-02-16 12:11:35,813] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 53
[2021-02-16 12:11:35,836] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-16 12:11:35,900] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-02-16 12:11:36,566] {process_utils.py:66} INFO - Process psutil.Process(pid=53, status='terminated', exitcode=1, started='12:11:28') (53) terminated with exit code 1
